version: '3'
services:
  site:
    container_name: site
    build: site
    ports:
      - "80:8000"
    volumes:
      - ./site:/var/www/html
    networks:
      - backend-network
      - frontend-network
      -
  users:
    container_name: users
    build: users

    volumes:
      - ./users:/var/www/html
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
