

<form method='post' action="/login">
    <?php
    $this->flashSession->output();

        foreach ($form as $element) {

            $messages = $form->getMessagesFor(
                $element->getName()
            );

            if (count($messages)) {

                echo '<div class="messages">';

                foreach ($messages as $message) {
                    echo $message;
                }

                echo '</div>';
            }

            echo '<p>';
            echo '<label for="' .
                $element->getName() .
                '">' .
                $element->getLabel() .
                '</label>'
            ;

            echo $element;
            echo '</p>';
        }
    ?>

</form>